### PR TITLE
Decryption and decompression fixes and changes

### LINKED ISSUE #5: camel data is zlib compressed
Unsure what the implications are for whatever flags point to ZStd instead of ZLib, but forcing ZLib allowed everything to be extracted successfully.

### PR DESCRIPTION
**Pull request by CosmicDreamsOfCode**
- Move shared decryption code into a new method to clean up a bit
- Change decryption of assets to decrypt pages for compressed assets, this fixes assets with more than 1 compressed page failing to decrypt properly
- Fix an issue where assets with 1 compressed page would fail to decompress because the output buffer wasn't correctly sized
- Fix #5 by checking for the toc compression method when decompressing non-oodle assets 
- Fix localised assets and and part E slices still attempting to get data even if the sdfdata doesn't exist, return null for the former
- Change exposed Assets enumerable to a list of file names instead, this is more compatible with the methods we have in GameManager for getting asset data, also added a a method to get this list through the GameManager, as it was previously inaccessible

### CODE REVIEW

File: Galanthus/SdfToc.cs [hunk 1]
```diff
@@ -359,17 +342,25 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
...
 
-        return true;
+        if (File.Exists(path))
+        {
+            return true;
+        }
+        else
+        {
+            return false;
+        }
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:352]:
```suggestion
        return File.Exists(path);
```

File: Galanthus/SdfToc.cs [hunk 2]
```diff
@@ -380,8 +371,14 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
             }
 
             outBufferSize += (int)dataSlice.DecompressedSize;
+        }
 
+        // probably a localised file that isn't installed so just return null before we do anything
+        if (outBufferSize - ddsHeaderSize <= 0 && inAsset.DataSlices[0].DecompressedSize != 0)
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:377]: why do u check for DecompressedSize != 0 here?
are there assets who have their decompressed size set to 0

File: Galanthus/SdfToc.cs [hunk 3]
```diff
@@ -448,11 +412,33 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
                     for (int i = 0; i < dataSlice.PageSizes!.Count; i++)
                     {
                         int decompressedSize = (int)Math.Min(dataSlice.DecompressedSize - decompressedOffset, pageSize);
+                        if (dataSlice.PageSizes!.Count == 1)
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:415]:
```suggestion
                        if (dataSlice.PageSizes.Count == 1)
```

File: Galanthus/SdfToc.cs [hunk 4]
```diff
@@ -448,11 +412,33 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
...
+                            Block<byte> tempBuffer = new(compressedBuffer.Ptr, decompressedSize);
+                            tempBuffer.MarkMemoryAsFragile();
+
+                            // decrypt page
+                            if (dataSlice.IsEncrypted)
+                            {
+                                if (!DecryptBlock(m_header.Version, tempBuffer, ref outBuffer))
+                                {
+                                    Console.WriteLine("Page failed to decrypt!");
+                                    break;
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:433]:
```suggestion
                                    return null;
```

File: Galanthus/SdfToc.cs [hunk 5]
```diff
@@ -462,9 +448,30 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
                             Block<byte> tempBuffer = new(compressedBuffer.Ptr, dataSlice.PageSizes[i]);
                             tempBuffer.MarkMemoryAsFragile();
 
+                            // decrypt page
+                            if (dataSlice.IsEncrypted)
+                            {
+                                if (!DecryptBlock(m_header.Version, tempBuffer, ref tempBuffer))
+                                {
+                                    Console.WriteLine("Page failed to decrypt!");
+                                    break;
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:457]:
```suggestion
                                    return null;
```

File: Galanthus/SdfToc.cs [hunk 6]
```diff
@@ -484,7 +491,20 @@ public bool TryGetDataFile(DataSlice inSlice, [NotNullWhen(true)] out string? pa
...
                 else
                 {
-                    compressedBuffer.CopyTo(outBuffer, (int)dataSlice.DecompressedSize);
+                    // decrypt whole slice
+                    if (dataSlice.IsEncrypted)
+                    {
+                        if (!DecryptBlock(m_header.Version, compressedBuffer, ref outBuffer))
+                        {
+                            Console.WriteLine("Slice failed to decrypt!");
+                            break;
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:500]:
```suggestion
                            return null;
```

File: Galanthus/SdfToc.cs [hunk 7]
```diff
@@ -644,6 +664,40 @@ private static void ParseEntry(DataStream inStream, bool isSigned, string name,
         }
     }
 
+    public static unsafe bool DecryptBlock(uint tocVersion, Block<Byte> inBuf, ref Block<Byte> outBuf)
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:667]:
```suggestion
    public static unsafe bool DecryptBlock(uint inVersion, Block<Byte> inBuf, ref Block<Byte> outBuf)
```

File: Galanthus/SdfToc.cs [hunk 8]
```diff
@@ -644,6 +664,40 @@ private static void ParseEntry(DataStream inStream, bool isSigned, string name,
...
+    {
+        if (KeyManager.Key is null || KeyManager.Iv is null)
+        {
+            return false;
+        }
+
+        if (tocVersion >= 0x29 && inBuf.Size >= 8)
```
Comment (wannkunstbeikor) [inline Galanthus/SdfToc.cs:674]:
```suggestion
        if (inVersion >= 0x29 && inBuf.Size >= 8)
```

**Review by wannkunstbeikor — CHANGES_REQUESTED** [review]
just some small changes and one question, but looks good

File: Galanthus/SdfToc.cs (hunk 2 above)
Comment (CosmicDreamsOfCode) [reply Galanthus/SdfToc.cs:377]: I'm not sure, but there theoretically could be i guess so i wanted to account for that

Comment (wannkunstbeikor) [reply Galanthus/SdfToc.cs:370]: either way would a decompressed size of 0 nlt also be catched by the first check

Comment (CosmicDreamsOfCode) [reply Galanthus/SdfToc.cs:370]: wdym?
the goal of this check here is to return null for assets that aren't installed, so assets that have a size greater than 0, but that we couldn't get any data for (the outbuffer size would be 0 but the slice decompressed size wouldn't be)

Comment (wannkunstbeikor) [reply Galanthus/SdfToc.cs:370]: i mean if the outbuffer is empty we can just return null, since there wont be any slices with the size of 0

Comment (CosmicDreamsOfCode) [reply Galanthus/SdfToc.cs]: removed the extra check, leaving on the dds header thing though in case theres any localised textures

Comment (wannkunstbeikor) [reply Galanthus/SdfToc.cs]: sounds good

**Review by wannkunstbeikor — APPROVED** [review]
